### ISSUE TITLE
Calculate the linewidth automatically in plot methods

### ISSUE THREAD

**Issue by taironemagalhaes** [cegeme/iracema#59]
Currently the line width in the plot methods is affected by the length of the audio file. So, if the user does not set it manually, the line width might be too thin if the audio file is short, or too thick if the audio file is large. Ideally, the line width should be calculated automatically when not specified by the user as an input argument to the plot method (this can be implemented setting the keyword argument `linewidth=None`).

**Comment by ofefo** [comment]
Fixed with #62
