### ISSUE TITLE
Refactor plot methods

### ISSUE THREAD

**Issue by taironemagalhaes** [cegeme/iracema#60]
- Some of the plot methods in module `plot` are not supposed to be exposed by the API, since they are internal methods. Those methods are named `add_*_to_axes`. They should be preceded by an underscore.
- The logic implemented in the method `plot()` from the class `TimeSeries` should be moved to the module `plot.py` (probably as a new method), and this new method should be wraped by the current `plot`, to leave all the logic relative to plotting contained in the plot method. The current API for the `plot` method must not be modified.

**Comment by ofefo** [comment]
Implemented with #68
